env:
  browser: true
  commonjs: true
  es2021: true
  node: true
  jest/globals: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
plugins:
  - jest
rules:
  implicit-arrow-linebreak: 0
  operator-linebreak:
    - 2
    - after
  comma-dangle:
    - error
    - arrays: never
      objects: always-multiline
      imports: never
      exports: never
      functions: never
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
